name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install package
        run: pip3 install "."
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run Test
        run: bash ./run_all.sh
        working-directory: ./test
      - name: Upload Codecov Report
        working-directory: ./test
        run: bash <(curl -s https://codecov.io/bash) # In GitHub Actions, an upload token is not required.
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}